//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace werkbank.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("werkbank.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_backup {
            get {
                object obj = ResourceManager.GetObject("btn_backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_create {
            get {
                object obj = ResourceManager.GetObject("btn_create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_delete {
            get {
                object obj = ResourceManager.GetObject("btn_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_down {
            get {
                object obj = ResourceManager.GetObject("btn_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_edit {
            get {
                object obj = ResourceManager.GetObject("btn_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_history {
            get {
                object obj = ResourceManager.GetObject("btn_history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_open {
            get {
                object obj = ResourceManager.GetObject("btn_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_queue {
            get {
                object obj = ResourceManager.GetObject("btn_queue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_refresh {
            get {
                object obj = ResourceManager.GetObject("btn_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_reset {
            get {
                object obj = ResourceManager.GetObject("btn_reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_settings {
            get {
                object obj = ResourceManager.GetObject("btn_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_stats {
            get {
                object obj = ResourceManager.GetObject("btn_stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_up {
            get {
                object obj = ResourceManager.GetObject("btn_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_vscode {
            get {
                object obj = ResourceManager.GetObject("btn_vscode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_web {
            get {
                object obj = ResourceManager.GetObject("btn_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.cs diff=csharp.
        /// </summary>
        internal static string csharp_gitattributes {
            get {
                return ResourceManager.GetString("csharp_gitattributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Ignore Visual Studio temporary files, build results, and
        ///## files generated by popular Visual Studio add-ons.
        ///
        ///# User-specific files
        ///*.suo
        ///*.user
        ///*.sln.docstates
        ///.vs
        ///.werk
        ///
        ///# Build results
        ///
        ///[Dd]ebug/
        ///[Rr]elease/
        ///x64/
        ///[Bb]in/
        ///[Oo]bj/
        ///
        ///# MSTest test Results
        ///[Tt]est[Rr]esult*/
        ///[Bb]uild[Ll]og.*
        ///
        ///*_i.c
        ///*_p.c
        ///*_i.h
        ///*.ilk
        ///*.meta
        ///*.obj
        ///*.pch
        ///*.pdb
        ///*.pgc
        ///*.pgd
        ///*.rsp
        ///*.sbr
        ///*.tlb
        ///*.tli
        ///*.tlh
        ///*.tmp
        ///*.tmp_proj
        ///*.log
        ///*.vspscc
        ///*.vssscc
        ///.builds
        ///*.pidb
        ///*.log
        ///*.svclog
        ///*.scc
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csharp_gitignore {
            get {
                return ResourceManager.GetString("csharp_gitignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [*]
        ///indent_style = space
        ///indent_size = 2
        ///end_of_line = lf
        ///charset = utf-8
        ///trim_trailing_whitespace = true
        ///insert_final_newline = true
        ///
        ///[*.json]
        ///insert_final_newline = ignore
        ///
        ///[*.md]
        ///trim_trailing_whitespace = false
        ///.
        /// </summary>
        internal static string default_editorconfig {
            get {
                return ResourceManager.GetString("default_editorconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * text=auto eol=lf.
        /// </summary>
        internal static string default_gitattributes {
            get {
                return ResourceManager.GetString("default_gitattributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Uncomment these types if you want even more clean repository. But be careful.
        ///# It can make harm to an existing project source. Read explanations below.
        ///#
        ///# Resource files are binaries containing manifest, project icon and version info.
        ///# They can not be viewed as text or compared by diff-tools. Consider replacing them with .rc files.
        ///#*.res
        ///#
        ///# Type library file (binary). In old Delphi versions it should be stored.
        ///# Since Delphi 2009 it is produced from .ridl file and can safely be ignored.
        ///#*.tlb
        ///#
        ///# D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string delphi_gitignore {
            get {
                return ResourceManager.GetString("delphi_gitignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_search {
            get {
                object obj = ResourceManager.GetObject("edit_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_blank {
            get {
                object obj = ResourceManager.GetObject("icon_blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Java sources
        ///*.java          text diff=java
        ///*.kt            text diff=kotlin
        ///*.groovy        text diff=java
        ///*.scala         text diff=java
        ///*.gradle        text diff=java
        ///*.gradle.kts    text diff=kotlin
        ///
        ///# These files are text and should be normalized (Convert crlf =&gt; lf)
        ///*.css           text diff=css
        ///*.scss          text diff=css
        ///*.sass          text
        ///*.df            text
        ///*.htm           text diff=html
        ///*.html          text diff=html
        ///*.js            text
        ///*.jsp           text
        ///*.jspf         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string java_gitattributes {
            get {
                return ResourceManager.GetString("java_gitattributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Compiled class file
        ///*.class
        ///
        ///# Log file
        ///*.log
        ///
        ///# BlueJ files
        ///*.ctxt
        ///
        ///# Mobile Tools for Java (J2ME)
        ///.mtj.tmp/
        ///
        ///# Package Files #
        ///*.jar
        ///*.war
        ///*.nar
        ///*.ear
        ///*.zip
        ///*.tar.gz
        ///*.rar
        ///
        ///# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
        ///hs_err_pid*
        ///replay_pid*.
        /// </summary>
        internal static string java_gitignore {
            get {
                return ResourceManager.GetString("java_gitignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # See http://help.github.com/ignore-files/ for more about ignoring files.
        ///
        ///# compiled output
        ////dist
        ////tmp
        ////out-tsc
        ///
        ///# Runtime data
        ///pids
        ///*.pid
        ///*.seed
        ///*.pid.lock
        ///
        ///# Directory for instrumented libs generated by jscoverage/JSCover
        ///lib-cov
        ///
        ///# Coverage directory used by tools like istanbul
        ///coverage
        ///
        ///# nyc test coverage
        ///.nyc_output
        ///
        ///# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
        ///.grunt
        ///
        ///# Bower dependency directory (https://bower.io/)
        ///bower_components
        ///
        ///# node-waf configuration
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_gitignore {
            get {
                return ResourceManager.GetString("js_gitignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /vendor/
        ///node_modules/
        ///npm-debug.log
        ///yarn-error.log
        ///
        ///# Laravel 4 specific
        ///bootstrap/compiled.php
        ///app/storage/
        ///
        ///# Laravel 5 &amp; Lumen specific
        ///public/storage
        ///public/hot
        ///
        ///# Laravel 5 &amp; Lumen specific with changed public path
        ///public_html/storage
        ///public_html/hot
        ///
        ///storage/*.key
        ///.env
        ///Homestead.yaml
        ///Homestead.json
        ////.vagrant
        ///.phpunit.result.cache.
        /// </summary>
        internal static string php_gitignore {
            get {
                return ResourceManager.GetString("php_gitignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Byte-compiled / optimized / DLL files
        ///__pycache__/
        ///*.py[cod]
        ///*$py.class
        ///
        ///# C extensions
        ///*.so
        ///
        ///# Distribution / packaging
        ///.Python
        ///build/
        ///develop-eggs/
        ///dist/
        ///downloads/
        ///eggs/
        ///.eggs/
        ///lib/
        ///lib64/
        ///parts/
        ///sdist/
        ///var/
        ///wheels/
        ///share/python-wheels/
        ///*.egg-info/
        ///.installed.cfg
        ///*.egg
        ///MANIFEST
        ///
        ///# PyInstaller
        ///#  Usually these files are written by a python script from a template
        ///#  before PyInstaller builds the exe, so as to inject date/other infos into it.
        ///*.manifest
        ///*.spec
        ///
        ///# Installe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string python_gitignore {
            get {
                return ResourceManager.GetString("python_gitignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vault_archive {
            get {
                object obj = ResourceManager.GetObject("vault_archive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vault_cold {
            get {
                object obj = ResourceManager.GetObject("vault_cold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vault_hot {
            get {
                object obj = ResourceManager.GetObject("vault_hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
